include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "example/**"
    - "test/**"
  
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  
  errors:
    # Treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # Treat missing returns as a warning (not a hint)
    missing_return: warning
    # Allow having TODOs in the code
    todo: ignore
    # Allow having print statements in the code
    avoid_print: ignore

linter:
  rules:
    # Prefer single quotes where they won't require escaping
    prefer_single_quotes: true
    
    # Prefer double quotes where they would require escaping
    avoid_escaping_inner_quotes: true
    
    # Prefer const constructors
    prefer_const_constructors: true
    
    # Prefer const literals as parameters of const constructors
    prefer_const_literals_to_create_immutables: true
    
    # Prefer const declarations for variables that are never reassigned
    prefer_const_declarations: true
    
    # Prefer const with constant constructors
    prefer_const_constructors_in_immutables: true
    
    # Prefer final for variable declarations if they are not reassigned
    prefer_final_fields: true
    
    # Prefer final for local variables
    prefer_final_locals: true
    
    # Prefer final for parameters
    prefer_final_parameters: true
    
    # Prefer for in loops
    prefer_for_elements_to_map_fromIterable: true
    
    # Prefer if null operators
    prefer_if_null_operators: true
    
    # Prefer initializing formal parameters
    prefer_initializing_formals: true
    
    # Prefer is not empty
    prefer_is_not_empty: true
    
    # Prefer is not operator
    prefer_is_not_operator: true
    
    # Prefer iterable whereType
    prefer_iterable_whereType: true
    
    # Prefer null aware operators
    prefer_null_aware_operators: true
    
    # Prefer relative imports
    prefer_relative_imports: true
    
    # Prefer spread collections
    prefer_spread_collections: true
    
    # Prefer void to null
    prefer_void_to_null: true
    
    # Public member API docs
    public_member_api_docs: false
    
    # Require trailing commas
    require_trailing_commas: true
    
    # Sort child properties last
    sort_child_properties_last: true
    
    # Sort constructors first
    sort_constructors_first: true
    
    # Sort pub dependencies
    sort_pub_dependencies: true
    
    # Sort unnamed constructors first
    sort_unnamed_constructors_first: true
    
    # Type annotate public APIs
    type_annotate_public_apis: false
    
    # Unnecessary const
    unnecessary_const: true
    
    # Unnecessary new
    unnecessary_new: true
    
    # Unnecessary null aware assignment
    unnecessary_null_aware_assignments: true
    
    # Unnecessary null in if null operators
    unnecessary_null_in_if_null_operators: true
    
    # Unnecessary null checks
    unnecessary_null_checks: true
    
    # Unnecessary this
    unnecessary_this: true
    
    # Use function type syntax for parameters
    use_function_type_syntax_for_parameters: true
    
    # Use rethrow
    use_rethrow_when_possible: true
    
    # Use string buffers
    use_string_buffers: true
    
    # Use string in contains
    use_string_in_part_of_directives: true
