name: flutter_adaptive_theme
description: A Flutter package that automatically adapts your app's theme based on system settings, time of day, or user preferences with smooth transitions.
version: 0.0.2
homepage: https://github.com/dhia-bechattaoui/flutter_adaptive_theme

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  # No assets needed for this package 